<?php
/**
 * @var Tructt\HelloWorld\Block\Display $block
 */
$datas = $block->loadAllArticles();

?>
<?php
$collection = $block->loadAllArticles();
?>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
    <table class="data table" id="test-data-table">
        <caption class="table-caption">Vky Test Data</caption>
        <thead>
        <tr>
            <th scope="col" class="col title">Title</th>
            <th scope="col" class="col author">Author</th>
            <th scope="col" class="col content">Content</th>
            <th scope="col" class="col actions">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($data as $key => $post) {
            $id = $post['article_id'];
            echo '<tr>
                    <td>' . $post['article_id'] . '</td>
                    <td>' . $post['title'] . '</td>
                    <td>' . $post['content'] . '</td>
                    <td><a href="detail?id=' . $id . '">Detail</a></td>
                  </tr>';
        }
        ?>
        </tbody>
    </table>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>