<ol class="products list items product-items">
    <li class="item product product-item">
        <div class="product-item-info" data-container="product-">
            <a href="#" class="product photo product-item-photo" tabindex="-1">
            </a>
            <div class="product details product-item-details">
                <strong class="product name product-item-name">
                    <a class="product-item-link"
                       href="#">
                    </a>
                </strong>
                <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                        <div class="product description product-item-description">
                        </div>
                    </div>
                </div>
            </div>
    </li>
</ol>