<?php
$name = $block->getData('name');
$price = $block->getData('price');
$priceNew = $block->getData('priceNew');
$image = $block->getData('image');
$note = $block->getData('note');
?>


<ol class="products list items product-items" id="best-seller">
    <li class="item product product-item">
        <div class="product-item-info" data-container="product-grid">
            <a href="http://example.com/proteus-fitness-jackshirt.html" class="product photo product-item-photo"
               tabindex="-1">
                <span class="product-image-container" style="width:240px;">
                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                        <img class="product-image-photo"
                             src="<?= $image ?>"
                             max-width="240" max-height="300" alt="Proteus Fitness Jackshirt"></span>
                         </span>
            </a>
            <div class="product details product-item-details">
                <strong class="product name product-item-name">
                    <a class="product-item-link" href="#"><?= $name ?></a>
                </strong>
                <div class="line"></div>
                <div class="price-box price-final_price" data-role="priceBox" data-product-id="436"
                     data-price-box="product-id-436">
                    <span class="price-container price-final_price tax weee">
                            <span id="product-price-436" data-price-amount="45" data-price-type="finalPrice"
                                  class="price-wrapper price-old">
                                <span class="price">SGD <?= $price ?></span>
                            </span>
                            <span id="product-price-436" data-price-amount="45" data-price-type="finalPrice"
                                  class="price-wrapper new-price">
                                <span class="price">SGD <?= $priceNew ?></span>
                            </span>
                    </span>
                </div>
            </div>
            <?php if (isset($note)): ?>
                <div class="note"><?= $note ?></div>
            <?php endif; ?>
    </li>
</ol>
